# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainwindow2.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1064, 774)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pathLabel = QtWidgets.QLabel(self.centralwidget)
        self.pathLabel.setObjectName("pathLabel")
        self.verticalLayout.addWidget(self.pathLabel)
        self.imgWidget = QtWidgets.QWidget(self.centralwidget)
        self.imgWidget.setObjectName("imgWidget")
        self.verticalLayout.addWidget(self.imgWidget)
        self.infoLabel = QtWidgets.QLabel(self.centralwidget)
        self.infoLabel.setObjectName("infoLabel")
        self.verticalLayout.addWidget(self.infoLabel)
        self.resultTextEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.resultTextEdit.setObjectName("resultTextEdit")
        self.verticalLayout.addWidget(self.resultTextEdit)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.initTextEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(35)
        self.initTextEdit_2.setFont(font)
        self.initTextEdit_2.setObjectName("initTextEdit_2")
        self.gridLayout_3.addWidget(self.initTextEdit_2, 0, 1, 1, 1)
        self.initTextEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(35)
        self.initTextEdit_3.setFont(font)
        self.initTextEdit_3.setObjectName("initTextEdit_3")
        self.gridLayout_3.addWidget(self.initTextEdit_3, 0, 2, 1, 1)
        self.initTextEdit_1 = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(35)
        self.initTextEdit_1.setFont(font)
        self.initTextEdit_1.setObjectName("initTextEdit_1")
        self.gridLayout_3.addWidget(self.initTextEdit_1, 0, 0, 1, 1)
        self.initTextEdit_4 = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(35)
        self.initTextEdit_4.setFont(font)
        self.initTextEdit_4.setObjectName("initTextEdit_4")
        self.gridLayout_3.addWidget(self.initTextEdit_4, 1, 0, 1, 1)
        self.initTextEdit_5 = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(35)
        self.initTextEdit_5.setFont(font)
        self.initTextEdit_5.setObjectName("initTextEdit_5")
        self.gridLayout_3.addWidget(self.initTextEdit_5, 1, 1, 1, 1)
        self.initTextEdit_6 = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(35)
        self.initTextEdit_6.setFont(font)
        self.initTextEdit_6.setObjectName("initTextEdit_6")
        self.gridLayout_3.addWidget(self.initTextEdit_6, 1, 2, 1, 1)
        self.initTextEdit_9 = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(35)
        self.initTextEdit_9.setFont(font)
        self.initTextEdit_9.setObjectName("initTextEdit_9")
        self.gridLayout_3.addWidget(self.initTextEdit_9, 2, 2, 1, 1)
        self.initTextEdit_8 = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(35)
        self.initTextEdit_8.setFont(font)
        self.initTextEdit_8.setObjectName("initTextEdit_8")
        self.gridLayout_3.addWidget(self.initTextEdit_8, 2, 1, 1, 1)
        self.initTextEdit_7 = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(35)
        self.initTextEdit_7.setFont(font)
        self.initTextEdit_7.setObjectName("initTextEdit_7")
        self.gridLayout_3.addWidget(self.initTextEdit_7, 2, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.targetTextEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(35)
        self.targetTextEdit_2.setFont(font)
        self.targetTextEdit_2.setObjectName("targetTextEdit_2")
        self.gridLayout_4.addWidget(self.targetTextEdit_2, 0, 1, 1, 1)
        self.targetTextEdit_4 = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(35)
        self.targetTextEdit_4.setFont(font)
        self.targetTextEdit_4.setObjectName("targetTextEdit_4")
        self.gridLayout_4.addWidget(self.targetTextEdit_4, 1, 0, 1, 1)
        self.targetTextEdit_1 = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(35)
        self.targetTextEdit_1.setFont(font)
        self.targetTextEdit_1.setObjectName("targetTextEdit_1")
        self.gridLayout_4.addWidget(self.targetTextEdit_1, 0, 0, 1, 1)
        self.targetTextEdit_6 = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(35)
        self.targetTextEdit_6.setFont(font)
        self.targetTextEdit_6.setObjectName("targetTextEdit_6")
        self.gridLayout_4.addWidget(self.targetTextEdit_6, 1, 2, 1, 1)
        self.targetTextEdit_5 = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(35)
        self.targetTextEdit_5.setFont(font)
        self.targetTextEdit_5.setObjectName("targetTextEdit_5")
        self.gridLayout_4.addWidget(self.targetTextEdit_5, 1, 1, 1, 1)
        self.targetTextEdit_7 = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(35)
        self.targetTextEdit_7.setFont(font)
        self.targetTextEdit_7.setObjectName("targetTextEdit_7")
        self.gridLayout_4.addWidget(self.targetTextEdit_7, 2, 0, 1, 1)
        self.targetTextEdit_9 = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(35)
        self.targetTextEdit_9.setFont(font)
        self.targetTextEdit_9.setObjectName("targetTextEdit_9")
        self.gridLayout_4.addWidget(self.targetTextEdit_9, 2, 2, 1, 1)
        self.targetTextEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(35)
        self.targetTextEdit_3.setFont(font)
        self.targetTextEdit_3.setObjectName("targetTextEdit_3")
        self.gridLayout_4.addWidget(self.targetTextEdit_3, 0, 2, 1, 1)
        self.targetTextEdit_8 = QtWidgets.QTextEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(35)
        self.targetTextEdit_8.setFont(font)
        self.targetTextEdit_8.setObjectName("targetTextEdit_8")
        self.gridLayout_4.addWidget(self.targetTextEdit_8, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_4)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.radioButtonH1 = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButtonH1.sizePolicy().hasHeightForWidth())
        self.radioButtonH1.setSizePolicy(sizePolicy)
        self.radioButtonH1.setObjectName("radioButtonH1")
        self.verticalLayout_2.addWidget(self.radioButtonH1)
        self.radioButtonH2 = QtWidgets.QRadioButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButtonH2.sizePolicy().hasHeightForWidth())
        self.radioButtonH2.setSizePolicy(sizePolicy)
        self.radioButtonH2.setObjectName("radioButtonH2")
        self.verticalLayout_2.addWidget(self.radioButtonH2)
        self.startButton = QtWidgets.QPushButton(self.centralwidget)
        self.startButton.setObjectName("startButton")
        self.verticalLayout_2.addWidget(self.startButton)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout.setStretchFactor(self.verticalLayout, 3)
        self.horizontalLayout.setStretchFactor(self.verticalLayout_2, 1)
        self.label_9.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1064, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pathLabel.setText(_translate("MainWindow", "路径"))
        self.infoLabel.setText(_translate("MainWindow", "%s\t\t%10s\t\t%10s\t\t%10s" % ('最优节点', 'h(n)', 'f(n)', 'OPEN表节点数')))
        self.label_9.setText(_translate("MainWindow", "初始状态："))
        self.label_10.setText(_translate("MainWindow", "目标状态："))
        self.label_8.setText(_translate("MainWindow", "启发函数："))
        self.radioButtonH1.setText(_translate("MainWindow", "h1(放错位置的个数)"))
        self.radioButtonH2.setText(_translate("MainWindow", "h2(走到正确位置的步数和)"))
        self.startButton.setText(_translate("MainWindow", "开始"))

